ForumInsta/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('forum/', include('forum.urls')),
    path('news/', include('news.urls')),
    path('resources/', include('resources.urls')),
    path('events/', include('events.urls')),
    path('messaging/', include('messaging.urls')),
    path('accounts/', include('modelUser.urls')),
    path('',include('home.urls')),
    path('accounts/', include('allauth.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

api/urls.py
from rest_framework_simplejwt.views import TokenRefreshView

from api.views import messaging_views, news_views
from .views.user_views import (
    GoogleLogin,
    PasswordResetAPIView,
    PasswordResetConfirmAPIView,
    UserProfileUpdateView,
    UserRegisterAPIView,
    UserLoginView,
    UserProfileAPIView,
    PasswordChangeAPIView,
    UserLogoutView,
    get_user_groups,
    
)
from django.http import HttpResponse
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views.forum_views import (CategoryViewSet, NotificationViewSet, ReportAPIView, SubforumViewSet, ThreadViewSet,
                         PostViewSet, ReportView,UserPublicProfileView)

from .views import events_views


# URLs pour le forum

forum_urlpatterns= [
    # Catégories
    path('categories/', CategoryViewSet.as_view({'get': 'list'}), name='category-list'),
    path('categories/<int:pk>/', CategoryViewSet.as_view({'get': 'retrieve'}), name='category-detail'),
    path('categories/<int:pk>/subforums/', CategoryViewSet.as_view({'get': 'subforums'}), name='category-subforums'),
    # Sous-forums
    path('subforums/', SubforumViewSet.as_view({'get': 'list'}), name='subforum-list'),
    path('subforums/<str:slug>/', SubforumViewSet.as_view({'get': 'retrieve'}), name='subforum-detail'),
    path('subforums/<str:slug>/threads/', SubforumViewSet.as_view({'get': 'threads'}), name='subforum-threads'),
    # Threads
    path('threads/', ThreadViewSet.as_view({'get': 'list', 'post': 'create'}), name='thread-list'),
    path('threads/<str:slug>/', ThreadViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='thread-detail'),
    path('threads/<str:slug>/posts/', ThreadViewSet.as_view({'get': 'posts'}), name='thread-posts'),
    path('threads/<str:slug>/like/', ThreadViewSet.as_view({'post': 'like'}), name='thread-like'),
    path('threads/<str:slug>/close/', ThreadViewSet.as_view({'post': 'close'}), name='thread-close'),
    path('threads/<str:slug>/open/', ThreadViewSet.as_view({'post': 'open'}), name='thread-open'),
    path('threads/<str:slug>/toggle_close/', ThreadViewSet.as_view({'post': 'toggle_close'}), name='thread-toggle-close'),
    # Posts
    path('posts/', PostViewSet.as_view({'get': 'list', 'post': 'create'}), name='post-list'),
    path('posts/<int:pk>/like/', PostViewSet.as_view({'post': 'like'}), name='post-like'),
    path('posts/<int:pk>/', PostViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='post-detail'),
    # Signalements
    path('report/', ReportView.as_view(), name='report'),
    # Profils utilisateurs (si cette vue est dans l'app forum)
    path('users/<str:username>/', UserPublicProfileView.as_view(), name='user-public-profile'),
    
    #Signalement
    path('report/thread/<slug:thread_slug>/', ReportAPIView.as_view(), name='report-thread'),
    path('report/post/<int:post_id>/', ReportAPIView.as_view(), name='report-post'),
    path('report/users/<str:username>/', ReportAPIView.as_view(), name='report-user'),

    
    # Notifications
    path('notifications/', NotificationViewSet.as_view({'get': 'list'}), name='notification-list'),
    path('notifications/unread/', NotificationViewSet.as_view({'get': 'unread'}), name='notification-unread'),
    path('notifications/<int:pk>/mark-as-read/', NotificationViewSet.as_view({'post': 'mark_as_read'}), name='notification-mark-as-read'),
    path('notifications/mark-all-as-read/', NotificationViewSet.as_view({'post': 'mark_all_as_read'}), name='notification-mark-all-as-read'),
    path('notifications/count-unread/', NotificationViewSet.as_view({'get': 'count_unread'}), name='notification-count-unread'),

]

# URLs pour les utilisateurs et l'authentification
user_urlpatterns = [
    path('all-users/', messaging_views.UserListView.as_view(), name='user-list'),
    path('auth/register/', UserRegisterAPIView.as_view(), name='register'),
    path('auth/login/', UserLoginView.as_view(), name='login'),
    path('auth/logout/', UserLogoutView.as_view(), name='logout'),
    path('auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('auth/google/', GoogleLogin.as_view(), name='google_login'),
    path('profile/', UserProfileAPIView.as_view(), name='user_profile'),
    path('profile/edit/', UserProfileUpdateView.as_view(), name='profile-update'),
    path('password/change/', PasswordChangeAPIView.as_view(), name='password_change'),
    path('auth/password/reset/', PasswordResetAPIView.as_view(),name='password_reset'),
    path('auth/password/reset/confirm/<str:uidb36>/<str:key>/', PasswordResetConfirmAPIView.as_view(), name='password_reset_confirm'),
    path('auth/groups/', get_user_groups, name='user-groups'),
]

events_urlpatterns = [
    path('list/', events_views.EventListAPIView.as_view(), name='event-list'),
    path('create/', events_views.EventCreateAPIView.as_view(), name='event-create'),
    path('detail/<int:pk>/', events_views.EventDetailAPIView.as_view(), name='event-detail'),
    path('delete/<int:event_id>/', events_views.DeleteEventAPIView.as_view(), name='delete-event'),
    path('participate/<int:event_id>/', events_views.ParticipateEventAPIView.as_view(), name='participate-event'),
    path('<int:event_id>/attendees/', events_views.EventAttendeesAPIView.as_view(), name='event-attendees'),
]

news_urlpatterns = [
    path('articles/', news_views.NewsArticleViewSet.as_view({'get': 'list'}), name='articles-list'),
    path('sources/', news_views.NewsSourceViewSet.as_view({'get': 'list'}), name='sources-news'),
    ]

messaging_urlpatterns = [
    
    path('conversations/', messaging_views.MessageViewSet.as_view({'get': 'conversations'}), name='message-conversations'),
    path('thread/', messaging_views.MessageViewSet.as_view({'get': 'thread'}), name='message-thread'),
    path('messages/', messaging_views.MessageViewSet.as_view({'post': 'create'}), name='message-create'),
    path('mark_as_read/', messaging_views.MessageViewSet.as_view({'post': 'mark_as_read'}),  name='message-mark-read'),
    path('users/search/', messaging_views.UserSearchAPIView.as_view(),  name='user-search')
    
]

from django.urls import path
from .views.resources_views import (
    ResourceListAPIView,
    ImageResourceCreateAPIView,
    LinkResourceCreateAPIView,
    DocumentResourceCreateAPIView,
    VideoResourceCreateAPIView,
    ResourceDetailAPIView,
    ResourceSearchAPIView,
)

resource_urlpatterns = [
    path('list/', ResourceListAPIView.as_view(), name='resource-list'),
    path('create/image/', ImageResourceCreateAPIView.as_view(), name='image-resource-create'),
    path('create/link/', LinkResourceCreateAPIView.as_view(), name='link-resource-create'),
    path('create/document/', DocumentResourceCreateAPIView.as_view(), name='document-resource-create'),
    path('create/video/', VideoResourceCreateAPIView.as_view(), name='video-resource-create'),
    path('detail/<int:pk>/', ResourceDetailAPIView.as_view(), name='resource-detail'),
    path('search/', ResourceSearchAPIView.as_view(), name='resource-search'), 
]

urlpatterns = [
    path('forum/', include(forum_urlpatterns)),  # URL du forum
    path('user/', include(user_urlpatterns)),    # URL des utilisateurs
    path('events/', include(events_urlpatterns)), # URL des événements
    path('news/', include(news_urlpatterns)),    # URL des news
    path('resources/', include(resource_urlpatterns)),  # URL des ressources
    path('messaging/', include(messaging_urlpatterns)),  # URL des messages
]

forum/urls.py
from django.urls import path
from .views import category_detail, close_thread, create_thread, add_post_view, first_thread_congrats, forum_home_view, like_post, mark_as_read, notifications, profile_view, reopen_thread, report_view, search_view, subforum_view, create_thread_view, tagged, thread_view,delete_thread_view
from .views import like_thread
from forum import views

app_name = 'forum'

urlpatterns = [
    path('', forum_home_view, name='home'),
    path('subforum/<slug>/', subforum_view, name='subforum'),
    path('category/<slug:slug>/', category_detail, name='category'),
    path('subforum/<slug>/create_thread/', create_thread_view, name='create_thread'),
    
    path('create/', create_thread, name='create'), 
    path('thread/<slug:slug>/', thread_view, name='thread'),
    path('delete/<slug:slug>/',delete_thread_view,name='delete_thread'),
    path('thread/<slug:slug>/like/', like_thread, name='like_thread'),
    path('thread/update/<slug:slug>/', views.update_thread, name='update_thread'),
    path('post/update/<int:post_id>/', views.update_post, name='update_post'),
    path('thread/<slug:slug>/close/', close_thread, name='close_thread'),
    path('thread/<slug:slug>/reopen/', reopen_thread, name='reopen_thread'),
    
    path('search/', search_view, name='search'),
    path('profile/<str:username>/', profile_view, name='profile'),
    path('tag/<slug:slug>/', tagged, name='tagged'),
    path('report/<str:report_type>/<int:item_id>/', report_view, name='report'),
    path('first-thread-congrats/<slug:slug>/', first_thread_congrats, name='first_thread_congrats'),

    path('add_post/<int:thread_id>/', add_post_view, name='add_post'),
    path('post/<int:post_id>/like/', like_post, name='like_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    
    path('suspend_user/<int:user_id>/', views.suspend_user, name='suspend_user'),
    path('moderation_dashboard/', views.moderation_dashboard, name='moderation_dashboard'),
 
    path('notifications/', notifications, name='notifications'),
    path('notifications/read/<int:notification_id>/', mark_as_read, name='mark_as_read'),
]

home/urls.py
from django import views
from django.urls import path
from .views import about, auth_status, contact, custom_403, custom_404, discussions_view, faq, home, privacy, rules, send_email


urlpatterns = [
    path('',view=home,name='home'),
    path('discussions/', discussions_view, name='discussions'),
    path('404',view=custom_404,name='404'),
    path('403',view=custom_403,name='403'),
    path('faq',view=faq,name='faq'),
    path('privacy',view=privacy,name='privacy'),
    path('rules',view=rules,name='rules'),
    path('about',view=about,name='about'),
    path('contact',view=contact,name='contact'),
    path('send_email',view=send_email,name='send_email'),
    path('auth/status/', view=auth_status, name='auth_status'),


]



    

news/urls.py
from django.urls import path
from . import views


app_name = 'news'
urlpatterns = [

    # path('info/', views.radio_info_view, name='radio_info'),
    path('create_news', views.create_news, name='create_news'),
    path('news/', views.collect_news, name='news'),
]

resources/urls.py
from django.urls import path
from . import views

app_name= 'resources'
urlpatterns = [
    path('', views.resource_list, name='resource_list'),
    path('search/', views.search_resources, name='search_resources'),
    path('add/image/', views.add_image, name='add_image'),
    path('add/link/', views.add_link, name='add_link'),
    path('add/document/', views.add_document, name='add_document'),
    path('add/video/', views.add_video, name='add_video'),
    path('detail/<int:pk>/', views.resource_detail, name='resource_detail'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect
from forum.models import Subforum, Thread
from events.models import Event
from news.models import NewsArticle
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.core.mail import send_mail
from django.db.models import Count
from django.utils import timezone

@never_cache
def home(request):
    # 1. Événement phare (le prochain événement à venir)
    featured_event = Event.objects.filter(
        date__gte=timezone.now()
    ).order_by('date').first()

    # 2. Événements à venir (les 3 prochains)
    upcoming_events = Event.objects.filter(
        date__gte=timezone.now()
    ).order_by('date')[:3]

    # 3. Threads populaires (les plus actifs)
    hot_threads = Thread.objects.filter(is_closed=False).annotate(
        post_count=Count('posts'),
        
    ).select_related(
        'author',
        'subforum'
    ).prefetch_related(
        'posts'
    ).order_by(
        '-post_count'
    )[:6]  # 6 threads pour la grille 2x3

    # 4. Subforums populaires (avec le plus de threads)
    popular_subforums = Subforum.objects.annotate(
        thread_count=Count('threads'),
        post_count=Count('threads__posts')
    ).order_by(
        '-thread_count'
    )[:4]  # 4 subforums pour la grille

    # 5. Actualités importantes (les plus récentes ou marquées)
    important_news = NewsArticle.objects.filter(
        is_active=True 
    ).order_by(
        '-published_at'
    )[:4]  # 4 articles max

    context = {
        'featured_event': featured_event,
        'upcoming_events': upcoming_events,
        'hot_threads': hot_threads,
        'popular_subforums': popular_subforums,
        'important_news': important_news,
    }

    return render(request, 'home/home.html', context)

@login_required
def discussions_view(request):
    threads = Thread.objects.prefetch_related('posts').all()
    subforums = Subforum.objects.all()

    # Ajouter les trois premiers posts à chaque thread et filtrer les threads sans slug
    valid_threads = []
    for thread in threads:
        if thread.slug:
            thread.top_posts = thread.posts.all()[:3]
            valid_threads.append(thread)

    return render(request, 'home/discussions.html', {
        'threads': valid_threads,
        'subforums': subforums,
    })



def custom_404(request, exception):
    return render(request, '404.html', status=404)

def custom_403(request, exception):
    return render(request, '403.html', status=403)

def privacy(request):
    return render(request,'privacy_policies.html')
def faq(request):
    return render(request,'faq.html')
def rules(request):
    return render(request,'rules.html')
def about(request):
    return render(request,'about.html')
def contact(request):
    return render(request,'contact.html')

def send_email(request):
    if request.method == 'POST':
        user_email = request.POST.get('email')
        message = request.POST.get('message')
        
        # Envoi de l'email
        send_mail(
            'Contact depuis InstaForum',
            message,
            user_email,  
            ['instaforum2025@gmail.com'],
        )
        return redirect('home')  
    return render(request, 'contact.html')



def auth_status(request):
    return JsonResponse({
        'auth_status': request.user.is_authenticated
    })
    

home/templates/home/discussions.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load l10n %}

{% block title %}
{% trans "Discussions" %}|InstaForum
{% endblock title %}
{% block link %}
<link rel="stylesheet" href="{% static 'css/discussions.css' %}">
{% endblock link %}

{% block content %}
<div class="container">
    <div class="scroll-container">
        <button class="arrow left-arrow ri-arrow-left-s-line"></button>
        <div class="grids-container">
            <div class="grid-row" id="gridRow1">
                {% for subforum in subforums %}
                {% if forloop.counter0|divisibleby:2 %}
                <div class="grid-item">
                    <a href="{% url 'forum:subforum' slug=subforum.slug %}">
                        {{ subforum.title }}
                    </a>
                </div>
                {% endif %}
                {% endfor %}
            </div>
            <div class="grid-row" id="gridRow2">
                {% for subforum in subforums %}
                {% if not forloop.counter0|divisibleby:2 %}
                <div class="grid-item">
                    <a href="{% url 'forum:subforum' slug=subforum.slug %}">
                        {{ subforum.title }}
                    </a>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <button class="arrow right-arrow ri-arrow-right-s-line"></button>
    </div>

    <div class="discussions-container">
        <h1>{% trans 'Discussions' %}</h1>
        {% for thread in threads %}
        <a href="{% url 'forum:thread' slug=thread.slug %}" class="thread-link">
            <div class="thread-item">
                <p>
                    <img src="{% if thread.author.profile_image %}{{ thread.author.profile_image.url }}{% else %}{% static 'images/default_profile.png' %}{% endif %}"
                        alt="Profile image" class="profile-image">
                    <span class="author-link">
                        {{ thread.author.name }}
                    </span> | {% blocktrans with date=thread.created_at|localize %}Le : {{ date }}{% endblocktrans %}
                </p>
                <h3>{{ thread.title }}</h3>
                <h5>{{ thread.content|truncatewords:60 }}</h5>
                <div class="posts">
                    {% with thread.posts.count as total_posts %}
                    <h4>
                        {% blocktrans count counter=total_posts %}
                        {{ counter }} réponse associée :
                        {% plural %}
                        {{ counter }} réponses associées :
                        {% endblocktrans %}
                    </h4>
                    {% endwith %}
                    <ul>
                        {% for post in thread.top_posts %}
                        <li>{{ post.content|truncatewords:30 }}</li>
                        {% empty %}
                        <p class="no-posts-message">{% trans 'Soyez le premier à poster sur ce thread !' %} </p>
                        {% endfor %}
                    </ul>
                </div>
                <h3><i style="color: var(--primary-color);" >{{ thread.subforum }}</i></h3>
            </div>
        </a>
        {% endfor %}
    </div>

    <button id="scrollToTopBtn" class="scroll-to-top">&#8679;</button>
</div>

{% endblock content %}



{% block javascript %}
{{ block.super }}
<script src="{% static 'js/discussions.js' %}"></script>
{% endblock javascript %}

home/templates/home/home.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load l10n %}

{% block link %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock link %}

{% block content %}

<div class="home-container">
    <!-- Hero Section - Événement Principal -->
    {% if featured_event %}
    <div class="hero-event">
        <div class="hero-content">
            <span class="hero-badge">{% trans "ÉVÉNEMENT PHARE" %}</span>
            <h1>{{ featured_event.title }}</h1>
            <div class="hero-meta">
                <span><i class="ri-calendar-line"></i> {% blocktrans with date=featured_event.date|localize %}{{ date }}{% endblocktrans %}</span>
                <span><i class="ri-time-line"></i> {% blocktrans with time=featured_event.date|time %}{{ time }}{% endblocktrans %}</span>
                <span><i class="ri-map-pin-line"></i> {{ featured_event.location }}</span>
            </div>
            <a href="{% url 'event_detail' featured_event.id %}" class="hero-button">{% trans "Découvrir" %} →</a>
        </div>
        {% if featured_event.image %}
        <div class="hero-image">
            <img src="{{ featured_event.image.url }}" alt="{{ featured_event.title }}">
        </div>
        {% endif %}
    </div>
    {% endif %}

    <!-- Grid Principale -->
    <div class="dynamic-grid">
        <!-- Section Threads (Large) -->
        <div class="card threads-card">
            <h2 class="section-title"><i class="ri-chat-3-line"></i> {% trans "Discussions Actives" %}</h2>
            <div class="threads-grid">
                {% for thread in hot_threads %}
                <a href="{% url 'forum:thread' slug=thread.slug %}" class="thread-card">
                    <div class="thread-header">
                        <img src="{{ thread.author.profile_image.url }}" alt="{{ thread.author.name }}"
                            class="thread-avatar">
                        <div>
                            <h3>{{ thread.title }}</h3>
                            <span>{% blocktrans with author=thread.author.name date=thread.created_at %}Par {{ author }} | le {{ date }}{% endblocktrans %}</span>
                        </div>
                    </div>
                    {% if thread.image %}
                    <div class="thread-image">
                        <img src="{{ thread.image.url }}" alt="{{ thread.title }}">
                    </div>
                    {% endif %}
                    <div class="thread-stats">
                        <span><i class="ri-message-2-line"></i> {% blocktrans count counter=thread.post_count %}{{ counter }} réponse{% plural %}{{ counter }} réponses{% endblocktrans %}</span>
                    </div>
                </a>
                {% endfor %}
            </div>
            <a href="{% url 'discussions' %}" class="see-all-button">{% trans "Voir toutes les discussions" %} →</a>
        </div>

        <!-- Section Événements (Vertical) -->
        <div class="card events-card">
            <h2 class="section-title"><i class="ri-calendar-event-line"></i> {% trans "Prochains Événements" %}</h2>
            <div class="events-vertical">
                {% for event in upcoming_events %}
                <a href="{% url 'event_detail' event.id %}" class="event-vertical">
                    <div class="event-date">
                        <span class="event-day">{{ event.date|date:"d" }}</span>
                        <span class="event-month">{{ event.date|date:"M"|upper }}</span>
                    </div>
                    <div class="event-content">
                        <h3>{{ event.title }}</h3>
                        <p>{{ event.description|truncatechars:80 }}</p>
                        <div class="event-meta">
                            <span><i class="ri-time-line"></i> {{ event.date|time }}</span>
                            <span><i class="ri-map-pin-line"></i> {{ event.location }}</span>
                        </div>
                    </div>
                    {% if event.image %}
                    <div class="event-thumbnail">
                        <img src="{{ event.image.url }}" alt="{{ event.title }}">
                    </div>
                    {% endif %}
                </a>
                {% endfor %}
            </div>
        </div>

        <!-- Section Actualités (Compacte) -->
        <div class="card news-card">
            <h2 class="section-title"><i class="ri-newspaper-line"></i> {% trans "À ne pas manquer" %}</h2>
            <div class="news-list">
                {% for article in important_news %}
                <a href="{{ article.url }}" class="news-item">
                    <div class="news-content">
                        <span class="news-category">{{ article.category }}</span>
                        <h3>{{ article.title }}</h3>
                        <p>{{ article.description|truncatechars:100 }}</p>
                    </div>
                    {% if article.image_url %}
                    <div class="news-image">
                        <img src="{{ article.image_url }}" alt="{{ article.title }}">
                    </div>
                    {% endif %}
                </a>
                {% endfor %}
            </div>
            <div class="news-footer">
                <a href="{% url 'news:news' %}" class="see-more-btn">{% trans "Voir Plus" %} <i class="ri-arrow-right-line"></i></a>
            </div>
        </div>

        <!-- Section Ressources (Carrés) -->
        <div class="card resources-card">
            <h2 class="section-title"><i class="ri-bookmark-line"></i> {% trans "Ressources Pratiques" %}</h2>
            <div class="resources-grid">
                <a href="{% url 'resources:resource_list' %}" class="resource-square">
                    <div class="resource-icon">
                        <i class="ri-book-2-fill"></i>
                    </div>
                    <h3>{% trans "Bibliothèque" %}</h3>
                </a>
                <a href="{% url 'resources:resource_list' %}" class="resource-square">
                    <div class="resource-icon">
                        <i class="ri-video-fill"></i>
                    </div>
                    <h3>{% trans "Tutoriels" %}</h3>
                </a>
                <a href="{% url 'resources:resource_list' %}" class="resource-square">
                    <div class="resource-icon">
                        <i class="ri-tools-fill"></i>
                    </div>
                    <h3>{% trans "Outils" %}</h3>
                </a>
                <a href="{% url 'faq' %}" class="resource-square">
                    <div class="resource-icon">
                        <i class="ri-question-fill"></i>
                    </div>
                    <h3>{% trans "FAQ" %}</h3>
                </a>
            </div>
        </div>

        <!-- Section Forum (Subforums) -->
        <div class="card forums-card">
            <h2 class="section-title"><i class="ri-community-line"></i> {% trans "Rejoignez la discussion" %}</h2>
            <div class="subforums-grid">
                {% for subforum in popular_subforums %}
                <a href="{% url 'forum:subforum' slug=subforum.slug %}" class="subforum-card">
                    {% if subforum.image %}
                    <div class="subforum-image">
                        <img src="{{ subforum.image.url }}" alt="{{ subforum.title }}">
                    </div>
                    {% endif %}
                    <div class="subforum-content">
                        <h3>{{ subforum.title }}</h3>
                        <p>{{ subforum.description|truncatechars:80 }}</p>
                        <div class="subforum-stats">
                            <span>{% blocktrans count counter=subforum.thread_count %}{{ counter }} threads{% plural %}{{ counter }} threads{% endblocktrans %}</span>
                            <span>{% blocktrans count counter=subforum.post_count %}{{ counter }} réponse{% plural %}{{ counter }} réponses{% endblocktrans %}</span>
                        </div>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block javascript %}
{{ block.super }}
<script src="{% static 'js/home.js' %}"></script>
{% endblock javascript %}