ForumInsta/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('forum/', include('forum.urls')),
    path('news/', include('news.urls')),
    path('resources/', include('resources.urls')),
    path('events/', include('events.urls')),
    path('messaging/', include('messaging.urls')),
    path('accounts/', include('modelUser.urls')),
    path('',include('home.urls')),
    path('accounts/', include('allauth.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

api/urls.py
from rest_framework_simplejwt.views import TokenRefreshView

from api.views import messaging_views, news_views
from .views.user_views import (
    GoogleLogin,
    PasswordResetAPIView,
    PasswordResetConfirmAPIView,
    UserProfileUpdateView,
    UserRegisterAPIView,
    UserLoginView,
    UserProfileAPIView,
    PasswordChangeAPIView,
    UserLogoutView,
    get_user_groups,
    
)
from django.http import HttpResponse
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views.forum_views import (CategoryViewSet, NotificationViewSet, ReportAPIView, SubforumViewSet, ThreadViewSet,
                         PostViewSet, ReportView,UserPublicProfileView)

from .views import events_views


# URLs pour le forum

forum_urlpatterns= [
    # Catégories
    path('categories/', CategoryViewSet.as_view({'get': 'list'}), name='category-list'),
    path('categories/<int:pk>/', CategoryViewSet.as_view({'get': 'retrieve'}), name='category-detail'),
    path('categories/<int:pk>/subforums/', CategoryViewSet.as_view({'get': 'subforums'}), name='category-subforums'),
    # Sous-forums
    path('subforums/', SubforumViewSet.as_view({'get': 'list'}), name='subforum-list'),
    path('subforums/<str:slug>/', SubforumViewSet.as_view({'get': 'retrieve'}), name='subforum-detail'),
    path('subforums/<str:slug>/threads/', SubforumViewSet.as_view({'get': 'threads'}), name='subforum-threads'),
    # Threads
    path('threads/', ThreadViewSet.as_view({'get': 'list', 'post': 'create'}), name='thread-list'),
    path('threads/<str:slug>/', ThreadViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='thread-detail'),
    path('threads/<str:slug>/posts/', ThreadViewSet.as_view({'get': 'posts'}), name='thread-posts'),
    path('threads/<str:slug>/like/', ThreadViewSet.as_view({'post': 'like'}), name='thread-like'),
    path('threads/<str:slug>/close/', ThreadViewSet.as_view({'post': 'close'}), name='thread-close'),
    path('threads/<str:slug>/open/', ThreadViewSet.as_view({'post': 'open'}), name='thread-open'),
    path('threads/<str:slug>/toggle_close/', ThreadViewSet.as_view({'post': 'toggle_close'}), name='thread-toggle-close'),
    # Posts
    path('posts/', PostViewSet.as_view({'get': 'list', 'post': 'create'}), name='post-list'),
    path('posts/<int:pk>/like/', PostViewSet.as_view({'post': 'like'}), name='post-like'),
    path('posts/<int:pk>/', PostViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='post-detail'),
    # Signalements
    path('report/', ReportView.as_view(), name='report'),
    # Profils utilisateurs (si cette vue est dans l'app forum)
    path('users/<str:username>/', UserPublicProfileView.as_view(), name='user-public-profile'),
    
    #Signalement
    path('report/thread/<slug:thread_slug>/', ReportAPIView.as_view(), name='report-thread'),
    path('report/post/<int:post_id>/', ReportAPIView.as_view(), name='report-post'),
    path('report/users/<str:username>/', ReportAPIView.as_view(), name='report-user'),

    
    # Notifications
    path('notifications/', NotificationViewSet.as_view({'get': 'list'}), name='notification-list'),
    path('notifications/unread/', NotificationViewSet.as_view({'get': 'unread'}), name='notification-unread'),
    path('notifications/<int:pk>/mark-as-read/', NotificationViewSet.as_view({'post': 'mark_as_read'}), name='notification-mark-as-read'),
    path('notifications/mark-all-as-read/', NotificationViewSet.as_view({'post': 'mark_all_as_read'}), name='notification-mark-all-as-read'),
    path('notifications/count-unread/', NotificationViewSet.as_view({'get': 'count_unread'}), name='notification-count-unread'),

]

# URLs pour les utilisateurs et l'authentification
user_urlpatterns = [
    path('all-users/', messaging_views.UserListView.as_view(), name='user-list'),
    path('auth/register/', UserRegisterAPIView.as_view(), name='register'),
    path('auth/login/', UserLoginView.as_view(), name='login'),
    path('auth/logout/', UserLogoutView.as_view(), name='logout'),
    path('auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('auth/google/', GoogleLogin.as_view(), name='google_login'),
    path('profile/', UserProfileAPIView.as_view(), name='user_profile'),
    path('profile/edit/', UserProfileUpdateView.as_view(), name='profile-update'),
    path('password/change/', PasswordChangeAPIView.as_view(), name='password_change'),
    path('auth/password/reset/', PasswordResetAPIView.as_view(),name='password_reset'),
    path('auth/password/reset/confirm/<str:uidb36>/<str:key>/', PasswordResetConfirmAPIView.as_view(), name='password_reset_confirm'),
    path('auth/groups/', get_user_groups, name='user-groups'),
]

events_urlpatterns = [
    path('list/', events_views.EventListAPIView.as_view(), name='event-list'),
    path('create/', events_views.EventCreateAPIView.as_view(), name='event-create'),
    path('detail/<int:pk>/', events_views.EventDetailAPIView.as_view(), name='event-detail'),
    path('delete/<int:event_id>/', events_views.DeleteEventAPIView.as_view(), name='delete-event'),
    path('participate/<int:event_id>/', events_views.ParticipateEventAPIView.as_view(), name='participate-event'),
    path('<int:event_id>/attendees/', events_views.EventAttendeesAPIView.as_view(), name='event-attendees'),
]

news_urlpatterns = [
    path('articles/', news_views.NewsArticleViewSet.as_view({'get': 'list'}), name='articles-list'),
    path('sources/', news_views.NewsSourceViewSet.as_view({'get': 'list'}), name='sources-news'),
    ]

messaging_urlpatterns = [
    
    path('conversations/', messaging_views.MessageViewSet.as_view({'get': 'conversations'}), name='message-conversations'),
    path('thread/', messaging_views.MessageViewSet.as_view({'get': 'thread'}), name='message-thread'),
    path('messages/', messaging_views.MessageViewSet.as_view({'post': 'create'}), name='message-create'),
    path('mark_as_read/', messaging_views.MessageViewSet.as_view({'post': 'mark_as_read'}),  name='message-mark-read'),
    path('users/search/', messaging_views.UserSearchAPIView.as_view(),  name='user-search')
    
]

from django.urls import path
from .views.resources_views import (
    ResourceListAPIView,
    ImageResourceCreateAPIView,
    LinkResourceCreateAPIView,
    DocumentResourceCreateAPIView,
    VideoResourceCreateAPIView,
    ResourceDetailAPIView,
    ResourceSearchAPIView,
)

resource_urlpatterns = [
    path('list/', ResourceListAPIView.as_view(), name='resource-list'),
    path('create/image/', ImageResourceCreateAPIView.as_view(), name='image-resource-create'),
    path('create/link/', LinkResourceCreateAPIView.as_view(), name='link-resource-create'),
    path('create/document/', DocumentResourceCreateAPIView.as_view(), name='document-resource-create'),
    path('create/video/', VideoResourceCreateAPIView.as_view(), name='video-resource-create'),
    path('detail/<int:pk>/', ResourceDetailAPIView.as_view(), name='resource-detail'),
    path('search/', ResourceSearchAPIView.as_view(), name='resource-search'), 
]

urlpatterns = [
    path('forum/', include(forum_urlpatterns)),  # URL du forum
    path('user/', include(user_urlpatterns)),    # URL des utilisateurs
    path('events/', include(events_urlpatterns)), # URL des événements
    path('news/', include(news_urlpatterns)),    # URL des news
    path('resources/', include(resource_urlpatterns)),  # URL des ressources
    path('messaging/', include(messaging_urlpatterns)),  # URL des messages
]

forum/urls.py
from django.urls import path
from .views import category_detail, close_thread, create_thread, add_post_view, first_thread_congrats, forum_home_view, like_post, mark_as_read, notifications, profile_view, reopen_thread, report_view, search_view, subforum_view, create_thread_view, tagged, thread_view,delete_thread_view
from .views import like_thread
from forum import views

app_name = 'forum'

urlpatterns = [
    path('', forum_home_view, name='home'),
    path('subforum/<slug>/', subforum_view, name='subforum'),
    path('category/<slug:slug>/', category_detail, name='category'),
    path('subforum/<slug>/create_thread/', create_thread_view, name='create_thread'),
    
    path('create/', create_thread, name='create'), 
    path('thread/<slug:slug>/', thread_view, name='thread'),
    path('delete/<slug:slug>/',delete_thread_view,name='delete_thread'),
    path('thread/<slug:slug>/like/', like_thread, name='like_thread'),
    path('thread/update/<slug:slug>/', views.update_thread, name='update_thread'),
    path('post/update/<int:post_id>/', views.update_post, name='update_post'),
    path('thread/<slug:slug>/close/', close_thread, name='close_thread'),
    path('thread/<slug:slug>/reopen/', reopen_thread, name='reopen_thread'),
    
    path('search/', search_view, name='search'),
    path('profile/<str:username>/', profile_view, name='profile'),
    path('tag/<slug:slug>/', tagged, name='tagged'),
    path('report/<str:report_type>/<int:item_id>/', report_view, name='report'),
    path('first-thread-congrats/<slug:slug>/', first_thread_congrats, name='first_thread_congrats'),

    path('add_post/<int:thread_id>/', add_post_view, name='add_post'),
    path('post/<int:post_id>/like/', like_post, name='like_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    
    path('suspend_user/<int:user_id>/', views.suspend_user, name='suspend_user'),
    path('moderation_dashboard/', views.moderation_dashboard, name='moderation_dashboard'),
 
    path('notifications/', notifications, name='notifications'),
    path('notifications/read/<int:notification_id>/', mark_as_read, name='mark_as_read'),
]

home/urls.py
from django import views
from django.urls import path
from .views import about, auth_status, contact, custom_403, custom_404, discussions_view, faq, home, privacy, rules, send_email


urlpatterns = [
    path('',view=home,name='home'),
    path('discussions/', discussions_view, name='discussions'),
    path('404',view=custom_404,name='404'),
    path('403',view=custom_403,name='403'),
    path('faq',view=faq,name='faq'),
    path('privacy',view=privacy,name='privacy'),
    path('rules',view=rules,name='rules'),
    path('about',view=about,name='about'),
    path('contact',view=contact,name='contact'),
    path('send_email',view=send_email,name='send_email'),
    path('auth/status/', view=auth_status, name='auth_status'),


]



    

messaging/urls.py
# messaging/urls.py
from django.urls import path
from . import views


app_name = 'messaging'

urlpatterns = [
    path('', views.user_messages, name='user_messages'),
    path('thread/<str:username>/', views.thread_detail, name='thread_detail'),
    path('search_users/', views.search_users, name='search_users'),
    

]

    

news/urls.py
from django.urls import path
from . import views


app_name = 'news'
urlpatterns = [

    # path('info/', views.radio_info_view, name='radio_info'),
    path('create_news', views.create_news, name='create_news'),
    path('news/', views.collect_news, name='news'),
]

home/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models
from django.utils import timezone

from modelUser.models import User

class NewsSource(models.Model):
    name = models.CharField(max_length=1000, unique=True)
    url = models.URLField(blank=True, null=True)
    
    class Meta:
        verbose_name = "Source d'actualité"
        verbose_name_plural = "Sources d'actualités"
    
    def __str__(self):
        return self.name

class NewsArticle(models.Model):
    title = models.CharField(max_length=2000, verbose_name="Titre")
    description = models.TextField(verbose_name="Description")
    url = models.URLField(verbose_name="URL de l'article",max_length=500)
    image_url = models.URLField(blank=True, null=True, verbose_name="URL de l'image")
    source = models.ForeignKey(NewsSource, on_delete=models.CASCADE, verbose_name="Source")
    published_at = models.DateTimeField(verbose_name="Date de publication")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")
    
    # Champs optionnels pour plus de fonctionnalités
    category = models.CharField(max_length=1000, blank=True, verbose_name="Catégorie")
    views_count = models.IntegerField(default=0, verbose_name="Nombre de vues")
    is_active = models.BooleanField(default=True, verbose_name="Actif")
    
    class Meta:
        verbose_name = "Article"
        verbose_name_plural = "Articles"
        ordering = ['-published_at']
        indexes = [
            models.Index(fields=['-published_at']),
            models.Index(fields=['category']),
        ]
        # Éviter les doublons
        constraints = [
            models.UniqueConstraint(
                fields=['url', 'published_at'], 
                name='unique_article'
            )
        ]
    
    def __str__(self):
        return self.title

forum/forms.py
from django import forms

from forum.utils import remove_accents
from .models import Report, Subforum, Thread, Post
from taggit.forms import TagWidget
from django.utils.translation import gettext_lazy as _



class ThreadForm(forms.ModelForm):
    class Meta:
        model = Thread
        fields = ['title', 'content', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': _('Titre de votre fil de discussion')}),
            'content': forms.Textarea(attrs={'placeholder': _('Contenu de votre fil de discussion')}),
            'tags': TagWidget(attrs={'placeholder': _('Sélectionnez ou ajoutez des tags')}),
        }


class ThreadFormCreate(forms.ModelForm):
    subforum = forms.ModelChoiceField(
        queryset=Subforum.objects.all(),
        required=True,
        label=_('Forum'),
        widget=forms.Select(attrs={'placeholder': _('Sélectionnez un forum')})
    )

    class Meta:
        model = Thread
        fields = ['subforum', 'title', 'content', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': _('Titre de votre fil de discussion')}),
            'content': forms.Textarea(attrs={'placeholder': _('Contenu de votre fil de discussion')}),
            'tags': TagWidget(attrs={'placeholder': _('Ajoutez des tags separés par des virgules')}),
        }


    def save(self, commit=True):
        thread = super().save(commit=False)
        if commit:
            thread.save()
            # Normaliser les tags avant de les ajouter
            raw_tags = self.cleaned_data.get('tags')
            normalized_tags = [remove_accents(tag) for tag in raw_tags]
            thread.tags.set(normalized_tags)
        return thread


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content']
        labels = {
            'content': _('Message')
        }
        widgets = {
            'content': forms.Textarea(attrs={
                'id': 'comment',
                'class': 'form-control',
                'placeholder': _('Écrivez votre message ici...'),
                'rows': 3
            }),
        }



class SearchForm(forms.Form):
    query = forms.CharField(label='Rechercher', max_length=255, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': _('Rechercher dans le forum...')
    }))

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['report_type', 'report_reason']
        labels = {
            'report_type': _('Type de signalement'),
            'report_reason': _('Raison du signalement'),
        }
        widgets = {
            'report_type': forms.Select(attrs={'class': 'form-control'}),
            'report_reason': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 
                                                   'placeholder': _('Expliquez la raison du signalement')}),
        }




class ThreadFormUpdate(forms.ModelForm):
    class Meta:
        model = Thread
        fields = ['title', 'content', 'image', 'tags']

class PostFormUpdate(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content']

messaging/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Message

class MessageForm(forms.ModelForm):
    content = forms.CharField(
        required=True, 
        widget=forms.Textarea(attrs={'rows': 4, 'cols': 50, 'placeholder': _('Écrire votre message ici')})
    )
    
    class Meta:
        model = Message
        fields = ['content']
        labels = {
            'content': _('Message'),
        }

forum/templates/forum/create.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'Créer un Fil de Discussion' %}
{% endblock title %}
    
{% block link %}
<link rel="stylesheet" href="{% static 'css/create.css' %}">
{% endblock link %}
{% block content %}
<div class="form-container">
    <h2>{% trans 'Créer un Fil de Discussion' %}</h2>
    {% if form.errors %}
    <div class="alert alert-danger form-errors">
        {% for field, errors in form.errors.items %}
        {% for error in errors %}
        <p>{{ error }}</p>
        {% endfor %}
        {% endfor %}
    </div>
    {% endif %}

    {% if not user.is_active %}
    <div class="alert alert-danger">
        <p>{% trans 'Votre compte est suspendu pour 7 jours par le modérateur. Vous ne pouvez pas créer de fil de discussion ou répondre à des posts mais vous pouvez toujours les lire.' %}</p>
    </div>
    {% else %}
    <form method="POST" enctype="multipart/form-data" class="form-thread-create">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_subforum"><i class="fas fa-list icon"></i>{% trans 'Forum' %}</label>
            {{ form.subforum }}
        </div>

        <div class="form-group">
            <label for="id_title"><i class="fas fa-heading icon"></i> {% trans 'Titre' %}</label>
            {{ form.title }}
        </div>

        <div class="form-group">
            <label for="id_content"><i class="fas fa-align-left icon"></i>{% trans 'Contenu' %}</label>
            {{ form.content }}
        </div>

        <div class="form-group">
            <label for="id_tags"><i class="fas fa-tags icon"></i>{% trans 'Tags' %}</label>
            {{ form.tags }}
        </div>

        <button type="submit" class="btn btn-primary"><i class="fas fa-plus-circle icon"></i> {% trans 'Créer' %}</button>
    </form>
    {% endif %}
</div>

{% if form.errors %}
<div class="alert alert-danger form-errors">
    {% for field, errors in form.errors.items %}
    {% for error in errors %}
    <p>{{ error }}</p>
    {% endfor %}
    {% endfor %}
</div>
{% endif %}

{% comment %} {% if messages %}
<div class="alert alert-danger">
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
</div>
{% endif %} {% endcomment %}

{% endblock content %}

forum/templates/forum/moderation_dashboard.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}
{% trans "Tableau de Bord de Modération" %}
{% endblock title %}

{% block link %}
<link rel="stylesheet" href="{% static 'css/moderation.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
<!-- Ajoute Font Awesome pour les icônes -->
{% endblock link %}

{% block content %}
<div class="container">
    <h1>{% trans "Tableau de Bord de Modération" %}</h1>

    {% comment %} <div class="reported-posts">
        <h2>{% trans "Messages Signalés" %}</h2>
        <ul>
            {% for message in reported_messages %}
            <li>
                <p>
                    <a href="{% url 'messaging:thread_detail' message.sender.id %}#message-{{ message.id }}"
                        class="post-link">{% trans "Voir le Message dans la conversation" %}</a>
                    <span class="report-count">({{ message.report_count }} {% blocktrans %}
                        signalements{% endblocktrans %})</span>
                </p>
                <p>{{ message.content|truncatewords:30 }}</p>
                <p>{% trans "Envoyé par" %} : <strong>{{ message.sender.username }}</strong></p>
                <p>{% trans "A" %} : <strong>{{ message.receiver.username }}</strong></p>
                {% for report in reports %}
                {% if report.message.id == message.id %}
                <p class="report-info">{% trans "Signalé par" %} : <strong>{{ report.reported_by.username }}</strong> |
                    {% trans "Raison" %} : {{ report.report_reason }} | {% trans "Date" %} : {{ report.created_at }}</p>
                {% endif %}
                {% endfor %}
                <div class="icons">
                    <a href="{% url 'messaging:delete_message' message.id %} " class="
                        icon-btn">
                        <i class="fa fa-trash"></i> <!-- Icône de corbeille pour supprimer -->
                    </a>
                    <a href="{% url 'messaging:thread_detail' message.sender.id %}" class="icon-btn">
                        <i class="fa fa-eye"></i> <!-- Icône d'œil pour voir -->
                    </a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div> {% endcomment %}


    <div class="reported-threads">
        <h2>{% trans "Threads Signalés" %}</h2>
        <ul>
            {% for thread in reported_threads %}
            <li>
                <p>
                    <a href="{% url 'forum:thread' slug=thread.slug %}" class="thread-link">{{ thread.title }}</a>
                    <span class="report-count">({{ thread.report_count }} {% blocktrans %}signalements {% endblocktrans %})</span>
                </p>
                <p>{{ thread.content|truncatewords:30 }}</p>
                <p>{% trans "Auteur" %} : <strong>{{ thread.author.first_name }} {{ thread.author.last_name }}</strong></p>
                {% for report in reports %}
                {% if report.thread.id == thread.id %}
                <p class="report-info">{% trans "Signalé par" %} : <strong>{{ report.reported_by.first_name }} {{ report.reported_by.last_name }}</strong> |
                    {% trans "Raison" %} : {{ report.report_reason }} | {% trans "Date" %} : {{ report.created_at }}</p>
                {% endif %}
                {% endfor %}
                <div class="icons">
                    <a href="{% url 'forum:delete_thread' slug=thread.slug %}" class="icon-btn" title="{% trans 'Supprimer' %}">
                        <i class="fa fa-trash"></i> <!-- Icône de corbeille pour supprimer -->
                    </a>
                    <a href="{% url 'forum:thread' slug=thread.slug %}" class="icon-btn" title="{% trans 'Voir' %}">
                        <i class="fa fa-eye"></i> <!-- Icône d'œil pour voir -->
                    </a>
                    
                    <a href="{% url 'forum:close_thread' slug=thread.slug %}" class="icon-btn" title="{% trans 'Fermer' %}">
                        <i class="fa fa-times"></i> <!-- Icône de croix pour fermer -->
                    </a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>

    <div class="reported-posts">
        <h2>{% trans "Posts Signalés" %}</h2>
        <ul>
            {% for post in reported_posts %}
            <li>
                <p>
                    <a href="{% url 'forum:thread' slug=post.thread.slug %}#post-{{ post.id }}" class="post-link">{%
                        trans "Voir le post" %}</a>
                    <span class="report-count">({{ post.report_count }} {% blocktrans %} signalements {% endblocktrans %})</span>
                </p>
                <p>{{ post.content|truncatewords:30 }}</p>
                <p>{% trans "Auteur" %} : <strong>{{ post.author.first_name }} {{ post.author.last_name }}</strong></p>
                {% for report in reports %}
                {% if report.post.id == post.id %}
                <p class="report-info">{% trans "Signalé par" %} : <strong>{{ report.reported_by.first_name }} {{ report.reported_by.last_name }}</strong> |
                    {% trans "Raison" %} : {{ report.report_reason }} | {% trans "Date" %} : {{ report.created_at }}</p>
                {% endif %}
                {% endfor %}
                <div class="icons">
                    <a href="{% url 'forum:delete_post' post.id %}" class="icon-btn"title="{% trans 'Supprimer' %}">
                        <i class="fa fa-trash"></i> <!-- Icône de corbeille pour supprimer -->
                    </a>
                    <a href="{% url 'forum:thread' slug=post.thread.slug %}" class="icon-btn" title="{% trans 'Voir' %}">
                        <i class="fa fa-eye"></i> <!-- Icône d'œil pour voir -->
                    </a>
                </div>
            </li>
            {% empty %}
            <h4>{% trans "Aucun signalé" %} </h4>
            {% endfor %}
        </ul>
    </div>

    <div class="user-management">
        <h2>{% trans "Gestion des Utilisateurs" %}
            <span class="inactive-users-count">({% trans "Utilisateurs inactifs" %}: {{ inactive_users_count }})</span>
        </h2>
        <ul>
            {% for report in reports %}
            {% if report.reported_user %}
                <li>
                    <p>
                        <a href="{% url 'forum:profile' username=report.reported_user.username %}" >
                        {% trans "Utilisateur" %} : <strong class="post-link">{{ report.reported_user.name }}</strong></a>
                        <span class="report-count">({{ report.reported_user.report_count }} {% blocktrans %} signalements {% endblocktrans %})</span>
                    </p>
                    
                    
                    <p class="report-info">{% trans "Signalé par" %} : <strong>{{ report.reported_by.name }}</strong> |
                        {% trans "Raison" %} : {{ report.report_reason }} | {% trans "Date" %} : {{ report.created_at }}</p>
                    
                    <div class="icons">
                        <a href="{% url 'forum:suspend_user' report.reported_user.id %}" class="icon-btn" title= "{% trans 'Suspendre' %}">
                            <i class="fa fa-user-lock"></i>
                        </a>
                        <a href="{% url 'forum:profile' username=report.reported_user.username %}" class="icon-btn" title="{% trans 'Voir' %}">
                            <i class="fa fa-eye"></i>
                        </a>
                    </div>
                </li>
                {% endif %}
                    {% endfor %}
        </ul>
    </div>
    <!-- <a href="{% url 'news:create_news' %}" class="icon-btn" title= "{% trans 'Ajouter une information' %}">
        <i class="fa fa-plus"></i></a> -->
</div>
{% endblock content %}

{% block javascript %}
{{ block.super }}
{% endblock javascript %}

forum/templates/forum/update_post.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
{% trans 'Mettre à Jour le Post' %}
{% endblock %}

{% block content %}
<div class="main-container">
    <h2>{% trans "Mettre à Jour le Post" %}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">{% trans "Mettre à Jour" %}</button>
    </form>
    <a href="{% url 'forum:thread' slug=thread.slug %}" class="btn btn-secondary">{% trans "Annuler" %}</a>
</div>
{% endblock %}