ForumInsta/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('forum/', include('forum.urls')),
    path('news/', include('news.urls')),
    path('resources/', include('resources.urls')),
    path('events/', include('events.urls')),
    path('messaging/', include('messaging.urls')),
    path('accounts/', include('modelUser.urls')),
    path('',include('home.urls')),
    path('accounts/', include('allauth.urls')),
    # path('__debug__/', include('debug_toolbar.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

api/urls.py
from rest_framework_simplejwt.views import TokenRefreshView

from api.views import messaging_views, news_views
from .views.user_views import (
    GoogleLogin,
    PasswordResetAPIView,
    PasswordResetConfirmAPIView,
    UserProfileUpdateView,
    UserRegisterAPIView,
    UserLoginView,
    UserProfileAPIView,
    PasswordChangeAPIView,
    UserLogoutView,
    get_user_groups,
    
)
from django.http import HttpResponse
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views.forum_views import (CategoryViewSet, NotificationViewSet, ReportAPIView, SubforumViewSet, ThreadViewSet,
                         PostViewSet, ReportView,UserPublicProfileView)

from .views import events_views


# URLs pour le forum

forum_urlpatterns= [
    # Catégories
    path('categories/', CategoryViewSet.as_view({'get': 'list'}), name='category-list'),
    path('categories/<int:pk>/', CategoryViewSet.as_view({'get': 'retrieve'}), name='category-detail'),
    path('categories/<int:pk>/subforums/', CategoryViewSet.as_view({'get': 'subforums'}), name='category-subforums'),
    # Sous-forums
    path('subforums/', SubforumViewSet.as_view({'get': 'list'}), name='subforum-list'),
    path('subforums/<str:slug>/', SubforumViewSet.as_view({'get': 'retrieve'}), name='subforum-detail'),
    path('subforums/<str:slug>/threads/', SubforumViewSet.as_view({'get': 'threads'}), name='subforum-threads'),
    # Threads
    path('threads/', ThreadViewSet.as_view({'get': 'list', 'post': 'create'}), name='thread-list'),
    path('threads/<str:slug>/', ThreadViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='thread-detail'),
    path('threads/<str:slug>/posts/', ThreadViewSet.as_view({'get': 'posts'}), name='thread-posts'),
    path('threads/<str:slug>/like/', ThreadViewSet.as_view({'post': 'like'}), name='thread-like'),
    path('threads/<str:slug>/close/', ThreadViewSet.as_view({'post': 'close'}), name='thread-close'),
    path('threads/<str:slug>/open/', ThreadViewSet.as_view({'post': 'open'}), name='thread-open'),
    path('threads/<str:slug>/toggle_close/', ThreadViewSet.as_view({'post': 'toggle_close'}), name='thread-toggle-close'),
    # Posts
    path('posts/', PostViewSet.as_view({'get': 'list', 'post': 'create'}), name='post-list'),
    path('posts/<int:pk>/like/', PostViewSet.as_view({'post': 'like'}), name='post-like'),
    path('posts/<int:pk>/', PostViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='post-detail'),
    # Signalements
    path('report/', ReportView.as_view(), name='report'),
    # Profils utilisateurs (si cette vue est dans l'app forum)
    path('users/<str:username>/', UserPublicProfileView.as_view(), name='user-public-profile'),
    
    #Signalement
    path('report/thread/<slug:thread_slug>/', ReportAPIView.as_view(), name='report-thread'),
    path('report/post/<int:post_id>/', ReportAPIView.as_view(), name='report-post'),
    path('report/users/<str:username>/', ReportAPIView.as_view(), name='report-user'),

    
    # Notifications
    path('notifications/', NotificationViewSet.as_view({'get': 'list'}), name='notification-list'),
    path('notifications/unread/', NotificationViewSet.as_view({'get': 'unread'}), name='notification-unread'),
    path('notifications/<int:pk>/mark-as-read/', NotificationViewSet.as_view({'post': 'mark_as_read'}), name='notification-mark-as-read'),
    path('notifications/mark-all-as-read/', NotificationViewSet.as_view({'post': 'mark_all_as_read'}), name='notification-mark-all-as-read'),
    path('notifications/count-unread/', NotificationViewSet.as_view({'get': 'count_unread'}), name='notification-count-unread'),

]

# URLs pour les utilisateurs et l'authentification
user_urlpatterns = [
    path('all-users/', messaging_views.UserListView.as_view(), name='user-list'),
    path('auth/register/', UserRegisterAPIView.as_view(), name='register'),
    path('auth/login/', UserLoginView.as_view(), name='login'),
    path('auth/logout/', UserLogoutView.as_view(), name='logout'),
    path('auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('auth/google/', GoogleLogin.as_view(), name='google_login'),
    path('profile/', UserProfileAPIView.as_view(), name='user_profile'),
    path('profile/edit/', UserProfileUpdateView.as_view(), name='profile-update'),
    path('password/change/', PasswordChangeAPIView.as_view(), name='password_change'),
    path('auth/password/reset/', PasswordResetAPIView.as_view(),name='password_reset'),
    path('auth/password/reset/confirm/<str:uidb36>/<str:key>/', PasswordResetConfirmAPIView.as_view(), name='password_reset_confirm'),
    path('auth/groups/', get_user_groups, name='user-groups'),
]

events_urlpatterns = [
    path('list/', events_views.EventListAPIView.as_view(), name='event-list'),
    path('create/', events_views.EventCreateAPIView.as_view(), name='event-create'),
    path('detail/<int:pk>/', events_views.EventDetailAPIView.as_view(), name='event-detail'),
    path('delete/<int:event_id>/', events_views.DeleteEventAPIView.as_view(), name='delete-event'),
    path('participate/<int:event_id>/', events_views.ParticipateEventAPIView.as_view(), name='participate-event'),
    path('<int:event_id>/attendees/', events_views.EventAttendeesAPIView.as_view(), name='event-attendees'),
]

news_urlpatterns = [
    path('articles/', news_views.NewsArticleViewSet.as_view({'get': 'list'}), name='articles-list'),
    path('sources/', news_views.NewsSourceViewSet.as_view({'get': 'list'}), name='sources-news'),
    ]

messaging_urlpatterns = [
    
    path('conversations/', messaging_views.MessageViewSet.as_view({'get': 'conversations'}), name='message-conversations'),
    path('thread/', messaging_views.MessageViewSet.as_view({'get': 'thread'}), name='message-thread'),
    path('messages/', messaging_views.MessageViewSet.as_view({'post': 'create'}), name='message-create'),
    path('mark_as_read/', messaging_views.MessageViewSet.as_view({'post': 'mark_as_read'}),  name='message-mark-read'),
    path('users/search/', messaging_views.UserSearchAPIView.as_view(),  name='user-search')
    
]

from django.urls import path
from .views.resources_views import (
    ResourceListAPIView,
    ImageResourceCreateAPIView,
    LinkResourceCreateAPIView,
    DocumentResourceCreateAPIView,
    VideoResourceCreateAPIView,
    ResourceDetailAPIView,
    ResourceSearchAPIView,
)

resource_urlpatterns = [
    path('list/', ResourceListAPIView.as_view(), name='resource-list'),
    path('create/image/', ImageResourceCreateAPIView.as_view(), name='image-resource-create'),
    path('create/link/', LinkResourceCreateAPIView.as_view(), name='link-resource-create'),
    path('create/document/', DocumentResourceCreateAPIView.as_view(), name='document-resource-create'),
    path('create/video/', VideoResourceCreateAPIView.as_view(), name='video-resource-create'),
    path('detail/<int:pk>/', ResourceDetailAPIView.as_view(), name='resource-detail'),
    path('search/', ResourceSearchAPIView.as_view(), name='resource-search'), 
]

urlpatterns = [
    path('forum/', include(forum_urlpatterns)),  # URL du forum
    path('user/', include(user_urlpatterns)),    # URL des utilisateurs
    path('events/', include(events_urlpatterns)), # URL des événements
    path('news/', include(news_urlpatterns)),    # URL des news
    path('resources/', include(resource_urlpatterns)),  # URL des ressources
    path('messaging/', include(messaging_urlpatterns)),  # URL des messages
]

forum/urls.py
from django.urls import path
from .views import category_detail, close_thread, create_thread, add_post_view, first_thread_congrats, forum_home_view, like_post, mark_as_read, notifications, profile_view, reopen_thread, report_view, search_view, subforum_view, create_thread_view, tagged, thread_view,delete_thread_view
from .views import like_thread
from forum import views

app_name = 'forum'

urlpatterns = [
    path('', forum_home_view, name='home'),
    path('subforum/<slug>/', subforum_view, name='subforum'),
    path('category/<slug:slug>/', category_detail, name='category'),
    path('subforum/<slug>/create_thread/', create_thread_view, name='create_thread'),
    
    path('create/', create_thread, name='create'), 
    path('thread/<slug:slug>/', thread_view, name='thread'),
    path('delete/<slug:slug>/',delete_thread_view,name='delete_thread'),
    path('thread/<slug:slug>/like/', like_thread, name='like_thread'),
    path('thread/update/<slug:slug>/', views.update_thread, name='update_thread'),
    path('post/update/<int:post_id>/', views.update_post, name='update_post'),
    path('thread/<slug:slug>/close/', close_thread, name='close_thread'),
    path('thread/<slug:slug>/reopen/', reopen_thread, name='reopen_thread'),
    
    path('search/', search_view, name='search'),
    path('profile/<str:username>/', profile_view, name='profile'),
    path('tag/<slug:slug>/', tagged, name='tagged'),
    path('report/<str:report_type>/<int:item_id>/', report_view, name='report'),
    path('first-thread-congrats/<slug:slug>/', first_thread_congrats, name='first_thread_congrats'),

    path('add_post/<int:thread_id>/', add_post_view, name='add_post'),
    path('post/<int:post_id>/like/', like_post, name='like_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    
    path('suspend_user/<int:user_id>/', views.suspend_user, name='suspend_user'),
    path('moderation_dashboard/', views.moderation_dashboard, name='moderation_dashboard'),
 
    path('notifications/', notifications, name='notifications'),
    path('notifications/read/<int:notification_id>/', mark_as_read, name='mark_as_read'),
]

messaging/urls.py
# messaging/urls.py
from django.urls import path
from . import views


app_name = 'messaging'

urlpatterns = [
    path('', views.user_messages, name='user_messages'),
    path('thread/<str:username>/', views.thread_detail, name='thread_detail'),
    path('search_users/', views.search_users, name='search_users'),
    

]

    

news/urls.py
from django.urls import path
from . import views


app_name = 'news'
urlpatterns = [

    # path('info/', views.radio_info_view, name='radio_info'),
    path('create_news', views.create_news, name='create_news'),
    path('news/', views.collect_news, name='news'),
]

resources/urls.py
from django.urls import path
from . import views

app_name= 'resources'
urlpatterns = [
    path('', views.resource_list, name='resource_list'),
    path('search/', views.search_resources, name='search_resources'),
    path('add/image/', views.add_image, name='add_image'),
    path('add/link/', views.add_link, name='add_link'),
    path('add/document/', views.add_document, name='add_document'),
    path('add/video/', views.add_video, name='add_video'),
    path('detail/<int:pk>/', views.resource_detail, name='resource_detail'),
]

templates/includes/footer.html
{% load static %}
{% load i18n %}
{% load moderation_tags %}

<footer class="footer">
  <div class="footer-section">
    <h3 class="footer-title">{% trans "Liens Utiles" %}</h3>
    <ul class="footer-links">
      <li><a href="https://insta.td/" target="_blank">INSTA</a></li>
      <li><a href="{% url 'home' %}">{% trans "Accueil" %}</a></li>
      <li><a href="{% url 'about' %}">{% trans "À propos" %}</a></li>
      <li><a href="{% url 'faq' %}">{% trans "FAQ" %}</a></li>
      <li><a href="{% url 'rules' %}">{% trans "Règles du forum" %}</a></li>
      <li><a href="{% url 'privacy' %}">{% trans "Politique de confidentialité" %}</a></li>
      <li><a href="{% url 'contact' %}">{% trans "Contact" %}</a></li>
      {% load moderation_tags %}
      {% is_moderator request.user as is_moderator %}
      {% if is_moderator %}
      <li><a href="{% url 'forum:moderation_dashboard' %}">
        {% trans "Modération" %}</a>
      </li>
      {% endif %}
      {% if user.is_authenticated %}
        <li><a href="{% url 'account_logout' %}">{% trans "Déconnexion" %}</a></li>
      {% else %}
        <li><a href="{% url 'account_login' %}"> {% trans 'Connexion' %}</a></li>
      {% endif %}
    </ul>
  </div>
  
  <div class="footer-section">
    <h3 class="footer-title">{% trans "Nous contacter" %}</h3>
    <ul class="footer-contact">
      <li><i class="fas fa-envelope"></i> <a href="mailto:instaforum2025@gmail.com">instaforum2025@gmail.com</a></li>
      <li><i class="fas fa-map-marker-alt"></i> Rue de Goz-Beida, Abéché, Tchad</li>
    </ul>
  </div>

  <div class="footer-section">
    <h3 class="footer-title">{% trans "Réseaux Sociaux" %}</h3>
    <ul class="footer-social">
      <li><a href="https://www.facebook.com/people/%F0%9D%91%A8%F0%9D%91%A9%F0%9D%91%B2%F0%9D%91%A8%F0%9D%91%B9%F0%9D%91%B0%F0%9D%91%BF4/61560225823078/" target="_blank" rel="noopener noreferrer"
          title="{% trans 'Facebook' %}"><i class="fab fa-facebook-f"></i></a></li>
      <li><a href="https://twitter.com/" target="_blank" rel="noopener noreferrer" title="{% trans 'Twitter' %}"><i
            class="fab fa-twitter"></i></a></li>
      <li><a href="https://www.instagram.com/" target="_blank" rel="noopener noreferrer"
          title="{% trans 'Instagram' %}"><i class="fab fa-instagram"></i></a></li>
      <li><a href="https://www.linkedin.com/" target="_blank" rel="noopener noreferrer"
          title="{% trans 'LinkedIn' %}"><i class="fab fa-linkedin-in"></i></a></li>
    </ul>
  </div>

  <div class="footer-section footer-copyright">
    <p>&copy; 2025 Instaforum. {% trans "Tous droits réservés." %}</p>
  </div>
</footer>

templates/includes/navbar.html
{% load static %}
{% load i18n %}
{% load category_tags %}
{% load contributor_tags %}
{% load forum_stats_tags %}
{% load popular_categories_tags %}
{% load moderation_tags %}


{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}
<div class="navbar">
  <div class="logo"><a href="{% url 'home' %}">InstaForum</a></div>
  <div class="menu">
    <div class="menu-item nav_link"><a href="{% url 'news:news' %}"><i class="fas fa-newspaper"></i> {% trans "Actualités du Monde" %}</a></div>
    
    <!-- Groupe "Communauté" avec dropdown -->
    <div class="menu-item nav_link dropdown-trigger">
      <a href="#"><i class="fas fa-users"></i> {% trans "Communauté" %} <i class="fas fa-chevron-down dropdown-arrow"></i></a>
      <div class="dropdown">
        <a href="{% url 'forum:home' %}"><i class="fas fa-comments"></i> {% trans "Forum" %}</a>
        <a href="{% url 'discussions' %}"><i class="fas fa-comment-dots"></i> {% trans "Discussions" %}</a>
        <a href="{% url 'resources:resource_list' %}"><i class="fas fa-bookmark"></i> {% trans "Ressources" %}</a>
      </div>
    </div>
    
    <div class="menu-item nav_link"><a href="{% url 'event_list' %}"><i class="fas fa-calendar"></i> {% trans "Evénements" %}</a></div>
    
    <div class="menu-item nav_link dropdown-trigger">
      <a href="#"><i class="fas fa-language lang-icon"></i> <i class="fas fa-chevron-down dropdown-arrow"></i></a>
      <div class="dropdown">
        {% for language in languages %}
        <a href="/{{language.code}}">{{ language.name_local }}</a>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="profile">
    {% if user.is_authenticated %}
    <a href="{% url 'account_profile' %}" title="{% trans 'Votre profil' %}">
        <img src="{{ user.profile_image.url }}?v={% now 'U' %}" alt="{% trans 'Profil' %}">
    </a>
    <div class="notification-icon">
      <a href="{% url 'forum:notifications' %}" title="{% trans ' Vos notifications' %}">
        <i class="fas fa-bell notification-icon nav_link"></i>
        <span class="notification-count">{{ notification_count }}</span>
      </a>
    </div>
    {% else %}
    <a href="{% url 'account_login' %}" title="{% trans 'Se connecter' %}">
      <i class="ri-login-box-line nav_link"></i>
    </a>
    <a href="{% url 'account_signup' %}" title="{% trans 'S\'inscrire' %}">
      <i class="ri-user-add-line nav_link"></i>
    </a>
    {% endif %}
    <a href="#" onclick="toggleTheme()" title="{% trans 'Changer de thème' %}">
      <i id="theme-icon" class="ri-sun-line nav_link"></i>
    </a>
    <div class="edit">
      <a href="{% url 'forum:create' %}" title="{% trans 'Créer un thread' %}">
        <i class="ri-edit-line nav_link"></i>
      </a>
    </div>
  </div>


  <!-- Toggle pour le menu mobile -->
  <div class="mobile-menu-toggle" id="mobileMenuToggle">
    <i class="fas fa-bars"></i>
  </div>

  <!-- Menu mobile -->
  <div class="mobile-menu" id="mobileMenu">
    <div class="menu-item"><a href="{% url 'news:news' %}"><i class="fas fa-newspaper"></i>{% trans "Actualités" %}</a></div>
    <div class="menu-item"><a href="{% url 'forum:home' %}">{% trans "Forum" %}</a></div>
    <div class="menu-item"><a href="{% url 'discussions' %}"><i class="fas fa-comments"></i>
        {% trans "Discussions" %}</a></div>
    <div class="menu-item"><a href="{% url 'forum:create' %}"><i class="fas fa-edit"></i>
        {% trans "Créer un thread" %}</a></div>
    <div class="menu-item"><a href="{% url 'event_list' %}"><i class="fas fa-calendar"></i>
        {% trans "Evénements" %}</a>
    </div>
    {% is_moderator request.user as is_moderator %}
    {% if is_moderator %}
      <div class="menu-item"><a href="{% url 'create_event' %}"><i class="fas fa-edit"></i>
        {% trans "Créer un Evénement"%}</a></div>
    {% endif %}
    <div class="menu-item"><a href="{% url 'messaging:user_messages' %}"><i class="fas fa-envelope"></i>
        {% trans "Messagerie privée" %}</a></div>

    <div class="menu-item">
      <i class="fas fa-language lang-icon"></i>
      {% trans "Langues" %}
      <div class="dropdown">
        {% for language in languages %}
        <a href="/{{language.code}}"><i class="fas fa-angle-right"></i>{{ language.name_local }}</a>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% include 'includes/sidebar.html' %}

<div class="sidebar-toggle" id="sidebarToggle">
  <i class="fas fa-bars"></i>
</div>

<div class="overlay" id="overlay"></div>

templates/includes/navbar_categories.html
<ul class="navbar-categories">
    {% for category in categories %}
    <li class="navbar-category-item">
        <a href="#">
            <i class="fas fa-hand-point-right"></i> {{ category.name }}
        </a>
    </li>
    {% endfor %}
</ul>

templates/includes/navbar_forum_stats.html
{% load i18n %}

<div class="forum-stats section">
    <p>{% trans "Statistiques du forum" %}</p>
    <a href="{% url 'forum:home' %}"><i class="fas fa-comments"></i> {% trans "Forums" %} : {{ forum_count }}</a>
    <a href="{% url 'forum:home' %}"><i class="fas fa-users"></i> {% trans "Membres" %} : {{ member_count }}</a>
    <a href="{% url 'discussions' %}"><i class="fas fa-envelope"></i> {% trans "Threads" %} : {{ total_messages_count }}</a>
    <!-- <a href="#"><i class="fas fa-user-clock"></i> {% trans "Membres en ligne" %} : {{ online_members_count }}</a> -->
</div>

templates/includes/navbar_top_contributors.html
{% load static %}
{% load i18n %}

<div class="top-contributors section">
    <p>{% translate "Tops contributeurs" %}</p>
    {% for contributor in top_thread_authors %}
        <a href="{% url 'forum:profile' username=contributor.user.username %}">
            {% if contributor.user.profile_image %}
                <img src="{{ contributor.user.profile_image.url }}" alt="{% blocktranslate with name=contributor.user.name %}Photo de profil de {{ name }}{% endblocktranslate %}" class="profile-image">
            {% else %}
                <img src="{% static 'images/default_profile.png' %}" alt="{% blocktranslate with name=contributor.user.name %}Photo de profil par défaut de {{ name }}{% endblocktranslate %}" class="profile-image">
            {% endif %}
            {{ contributor.user.name }} - 
            {% blocktranslate count count=contributor.count %}
                {{ count }} thread
            {% plural %}
                {{ count }} threads
            {% endblocktranslate %}
        </a>
    {% endfor %}
    {% for contributor in top_post_authors %}
        <a href="{% url 'forum:profile' username=contributor.user.username %}">
            {% if contributor.user.profile_image %}
                <img src="{{ contributor.user.profile_image.url }}" alt="{% blocktranslate with name=contributor.user.name %}Photo de profil de {{ name }}{% endblocktranslate %}" class="profile-image">
            {% else %}
                <img src="{% static 'images/default_profile.png' %}" alt="{% blocktranslate with name=contributor.user.name %}Photo de profil par défaut de {{ name }}{% endblocktranslate %}" class="profile-image">
            {% endif %}
            {{ contributor.user.name }} - 
            {% blocktranslate count count=contributor.count %}
                {{ count }} post
            {% plural %}
                {{ count }} posts
            {% endblocktranslate %}
        </a>
    {% endfor %}
</div>

templates/includes/popular_categories.html
{% for category in categories %}
<div class="navbar-category-item">
  <i class="fas fa-hand-point-right">
  <a href="{% url 'forum:category' slug=category.slug %} ">
    {{ category.name }} </a>
  </i>
</div>
{% endfor %}

templates/includes/sidebar.html
{% load i18n %}
{% load static %}
{% load category_tags %}
{% load contributor_tags %}
{% load forum_stats_tags %}
{% load popular_categories_tags %}
{% load moderation_tags %}

<div class="sidebar" id="sidebar">
    <div class="sidebar-content">
      <!-- Profil de l'utilisateur -->
      {% if user.is_authenticated %}
      <a href="{% url 'account_profile' %}">
        <div class="user-profile section">
          <img src="{{ user.profile_image.url }}" alt="Profile">
          <p>{{user.first_name}} {{user.last_name}}</p>
        </div>
      </a>
      {% endif %}
      <!-- Navigation rapide -->
      <div class="home section">
        <a href="{% url 'home' %}"><i class="fas fa-home"></i>{% trans "Accueil" %}</a>
        {% if user.is_authenticated %}
        <a href="{% url 'messaging:user_messages' %}"><i class=" fas fa-envelope"></i>
          {% trans "Messagerie privée" %}</a>
          {% endif %}
          
        {% comment %} <a href="#"><i class="fas fa-star"></i> Sujets populaires</a> {% endcomment %}
        
        {% is_moderator request.user as is_moderator %}
        {% if is_moderator %}
        <a href="{% url 'forum:moderation_dashboard' %}"><i class="fas fa-user-shield"></i>
          {% trans "Modération" %}</a>
        <a href="{% url 'create_event' %}"><i class="fas fa-edit"></i> {% trans "Creer Evénement" %}</a>
        {% endif %}
      </div>
      
      <!-- Catégories de sujets -->
      <div class="categories section">
        <p>{% trans "Catégories populaires" %}</p>
         {% show_popular_categories %}
      </div>
  
      <!-- Statistiques du forum -->
      {% show_forum_stats %}
  
      <!-- Actualités du forum -->
      {% comment %} <div class="forum-news section">
        <p>Actualités du forum</p>
        <a href="#">Mise à jour du forum - Janvier 2024</a>
        <a href="#">Concours de publication - Février 2024</a>
      </div> {% endcomment %}
  
      <!-- Liens utiles -->
      <div class="utils-links section">
        <a href="{% url 'faq' %}"><i class="fas fa-question-circle"></i> {% trans "FAQ" %}</a>
        <a href="{% url 'rules' %}"><i class="fas fa-gavel"></i> {% trans "Règles du forum" %}</a>
        <a href="{% url 'privacy' %}"><i class="fas fa-shield-alt"></i> {% trans "Politique de confidentialité" %}</a>
        <a href="{% url 'contact' %}"><i class="fas fa-envelope"></i> {% trans "Contact/Support" %}</a>
      </div>
  
      <!-- Liens vers les réseaux sociaux -->
      <!-- <div class="social-links section">
        <p>{% trans "Suivez-nous" %}</p>
        <a href="https://www.facebook.com/people/%F0%9D%91%A8%F0%9D%91%A9%F0%9D%91%B2%F0%9D%91%A8%F0%9D%91%B9%F0%9D%91%B0%F0%9D%91%BF4/61560225823078/"><i class="fab fa-facebook"></i> {% trans "Facebook" %}</a>
        <a href="#"><i class="fab fa-twitter"></i> {% trans "Twitter" %}</a>
        <a href="#"><i class="fab fa-instagram"></i> {% trans "Instagram" %}</a>
        <a href="#"><i class="fas fa-envelope"></i> {% trans "Email" %}</a>
      </div> -->
  
      <!-- Tops contributeurs -->
       {% show_top_contributors %}
    </div>
  </div>